[gdrive_credentials]
type = "service_account"
project_id = "hr-streamlit-drive"
private_key_id = "8c0fb647f6001e66b8086fde95cbcd1cd14e8baa"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDcj/B0A+vyw4e8
QF+kFhqU6bluXaFIS+Uc75MmLVRD7YHOTdwPwEXvYBVAq05lwZZBgrF9gPfajmUF
OI8Gz1OfHeHyj8U75GIxvJwb2N3wx66GcAwnYVmRFQ+OSXGHaRQF3/ozdzYpJQpC
7iaVMKNCkyZPZN1t/vjvwgDRVx9jNrRWySydsOzbimh9Q8lkBCIsQcwXrSV1MNpV
vbpoza4nbRmqw5rcAn+faOPoP8lnq829T9IYcN0W/cuNw2+x0uUj0IreCK2z3T2W
nA4F+xCtXo2jAS+o0Pt6YACyw5N+rvQz7a2uIub4q3n6ewgQwnvvIMfb5JdMDYur
DfxzO9G7AgMBAAECggEAZtF23y5g1KeP5BMCQsTHGXonJirhn4k5whZwu1BQQuY6
J8kl9/XC5EcfQSlaf5cSC3H4ebAgWrMcpqVqD1ug+MD+bovU/wmFOPhasaSUOcVs
N2GOWOFJ1pdBzCuyj9RNMDvsMAe3qNCKiw7nz45/3O4p4sL7cmZ095ext+TsTdv6
BApvHS3eXfpoK68UrSIAaUV+2UU8qWrItu3YQ9FwUjXqXS2TROCp9Xl8hiDE8a0u
zK+KlYIksBGYMDQLvMHjg7HJsMyhDx3jTyRpfURwgAnPrglc/NUZOPIcm36DwDGR
NCr/UAqnyDtbXyA4qup1qi9tdBg1WOlPNRRMG5qZ6QKBgQDuQvgZb6YykaBzLiZv
78iIGgn2m13eQALATRo9D6EgKAQnC0aFYK2AoeXZDeXJ7D1clJZVIv28TCd0Rw8O
sT/ylFQTKrXrUHOc2bKRC56hHoi4JJTnXF/BlYqgp28TnpN03PpJWN1L0efO3eNG
N+iqLIMbjEvj9nu2P80Rn+L1tQKBgQDs+6NluHHzBvKHdlp5b8ClWPuxmTOEhd7K
DfJOEOdoDNk8Vgj3ZVQEXD757gHaqMEzoUjzOcT+VZcD8cbwminq3QB1B+k0bzyG
tg9dxpGDVnj+AnlczSqYcEohKPEkfeXXMRuIpA46Vh+rZH3iHXgNO2VxFs/ZqShJ
DUYnIhdPrwKBgGnyUYxN/2NBKk3NWb4wq8UJfyCvmZ/4asDECETarFU2NhJ+iw9I
HB603xYTffi6GdcPI4IcGyQd4PVtm5525u6hUnlrZpWKor4+d47T0efnQfhQG/59
Lv9P1eL2UQgyXXN7x7fR0iWi4yczt5pDxivVuz8GtcBanExANpn9tNh5AoGBAIS3
/O9316Eyb9s7hjniQzKW3ga9dOOwEXB5VQ0xXFeicnre+BCNV/tFKiPQjotF3UWr
+u30mYWSq4uS+UZAIF+fO6VPM+Sgs3YCOiLblRzH7eTbv9ogMM3EfU+K3VoBhBn7
L59buXgkSYI0OmfK9zP54rrt+qO8n4oh+/rolcOTAoGAd50D+2q/ikEN+UTXcizr
BDnTbZpBQ7KWb1mVf1M/SjZejbkgdMSucd4NNWJWVzv+Pl66wp2onuj+HnQ0tp3S
GH21GltiKMA0aGPxyg/GXZs/nbhty1315FZsLYdOfxU0Pu+uR/J8dYoAzKAyEUHD
vZIeZvMqd7draf0Oju+ye8E=
-----END PRIVATE KEY-----"""
client_email = "streamlit-drive@hr-streamlit-drive.iam.gserviceaccount.com"
client_id = "114344910969531670686"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-drive%40hr-streamlit-drive.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
